### ISSUE TITLE
unrecognized selector sent to instance userContentController:didReceiveScriptMessage

### ISSUE THREAD

**Issue by casche** [asultonov/nativescript-wkwebview#1]
Saw your post on [discourse](https://discourse.nativescript.org/t/error-while-sending-message-from-wkwebview-to-the-n-application/1414/1).

I'd like to use this issue to track if you have a fix available.

**Comment by asultonov** [comment]
Fixed [c59374d](https://github.com/asultonov/nativescript-wkwebview/commit/f7d18f0c86ce9c349c24ceaffc5f2d2870424caf).
